### ISSUE TITLE
Rename the project to `metaphrase` (or any other name)

### ISSUE THREAD

**Issue by Signez** [metaphrase-dev/metaphrase#53]
I strongly think that even if it sounded nice at the first place, the name of this project will hurt its adoption if it grows at some point.

It won't take much to rename it now, and I suggest the name `metaphrase` (which is an synonym of `translation` in English according to thesaurus.com), that could be easier to remember and search on the web!

(I would also suggest to move the repository to an organization that share the same name, to reduce the bus-factor, but it's up to you, dear @rlustin :))

**Comment by rlustin** [comment]
Project renamed to `metaphrase`. Metaphrase organization is already taken on GitHub. Do you have another proposition for the organization name?

**Comment by Signez** [comment]
Awesome 🥳 I'd suggest to name it `metaphrase-dev`, as I'll buy the `metaphrase.dev` domain in a moment.

**Comment by Signez** [comment]
(Domain [metaphrase.dev](http://metaphrase.dev) bought btw 🛒 ✨)

**Comment by rlustin** [comment]
Done!
